using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MSTest
{
    public class MSTestConst
    {
        public static string OrganisationIdKey = "app.organisationid";
        public static string ActivityIdKey = "flow.activity_id";
        public static int LocaleidValueNL = 1043;
        public static int LocaleidValueBE = 2060;
        public static string LocaleIdKey = "app.localeid";
        public static string CTanar = "app.t_anar";
        public static string CTanst = "app.t_anst";
        public static string CTaplst = "app.t_aplst";
        public static string CTat = "app.t_at";
        public static string CTcanr = "app.t_canr";
        public static string CTcap = "app.t_cap";
        public static string CTcc = "app.t_cc";
        public static string CTche = "app.t_che";
        public static string CTchr = "app.t_chr";
        public static string CTcon = "app.t_con";
        public static string CTdt = "app.t_dt";
        public static string CTeg = "app.t_eg";
        public static string CTflsel = "app.t_flsel";
        public static string CTfolr = "app.t_folr";
        public static string CTil = "app.t_il";
        public static string CTinstt = "app.t_instt";
        public static string CTls = "app.t_ls";
        public static string CTmat = "app.t_mat";
        public static string CTmmr = "app.t_mmr";
        public static string CTmmt = "app.t_mmt";
        public static string CTpc = "app.t_pc";
        public static string CTpg = "app.t_pg";
        public static string CTprio = "app.t_prio";
        public static string CTq = "app.t_q";
        public static string CTql = "app.t_ql";
        public static string CTreg = "app.t_reg";
        public static string CTsc = "app.t_sc";
        public static string CTsign = "app.t_sign";
        public static string CTso = "app.t_so";
        public static string CTsot = "app.t_sot";
        public static string CTsut = "app.t_sut";
        public static string CTw = "app.t_w";
        public static string CTwr = "app.t_wr";
        public static string CTyn = "app.t_yn";
        public static int CTanarValue = 118343536;
        public static int CTanstValue = 1365579903;
        public static int CTaplstValue = 1522104463;
        public static int CTatValue = 69575286;
        public static int CTcanrValue = 190623722;
        public static int CTcapValue = 46623209;
        public static int CTccValue = 998346671;
        public static int CTcheValue = 182291709;
        public static int CTchrValue = 1605580758;
        public static int CTconValue = 110623437;
        public static int CTdtValue = 1300303792;
        public static int CTegValue = 1746209371;
        public static int CTflselValue = 1717581157;
        public static int CTfolrValue = 1370487961;
        public static int CTilValue = 773577794;
        public static int CTinsttValue = 466100701;
        public static int CTlsValue = 517576882;
        public static int CTmatValue = 1424776183;
        public static int CTmmrValue = 349296354;
        public static int CTmmtValue = 2016778292;
        public static int CTpcValue = 710345645;
        public static int CTpgValue = 1618104805;
        public static int CTprioValue = 101575400;
        public static int CTqValue = 1490104349;
        public static int CTqlValue = 2053582354;
        public static int CTregValue = 1394104007;
        public static int CTscValue = 1174347298;
        public static int CTsignValue = 557349150;
        public static int CTsoValue = 581577110;
        public static int CTsotValue = 1989582126;
        public static int CTsutValue = 1106102981;
        public static int CTwValue = 1616776867;
        public static int CTwrValue = 86343422;
        public static int CTynValue = 176823792;
        public static string CTverifydt = "app.verifydt";
        public static string CTverifydtValue = "2011-10-21T09:33:14";
        public static string UserIdKey = "app.userid";
        public static int UserIdValueNL = 8;
        public static int CTuseridValueBE = 46;
        public static string CTHandtekeningOptie = "flow.HandtekeningOptie";
        public static int CTHandtekeningOptieValue;
        public static string CTscreenValueGM = "GM";
        public static string CTscreen = "flow.screen";
        public static string CThuurauto = "app.huurauto";
        public static int CThuurautoValue;
        public static int OrganisationIdNL = 2;
        public static int OrganisationIdBE = 10;
        public static string CTscreenValue = "";
        public static string CTstockid = "flow.stockid";
        public static string CTNull = "null";
        public static string CTmatid = "flow.matid";
        public static int CTmatidValue = 1;
        public static string CTStartDayLabourId = "app.StartDayLabourId";
        public static int CTStartDayLabourIdValue;
        public static string CTzoekValue = "1";
        public static object CTzoek = "flow.zoek";
        public static object CTcbBreekReden;
        public static object CTcbBreekRedenValue = "1";
        public static object CTtxtOpmerking;
        public static object CTtxtOpmerkingValue = "2";
        public static object CTherkomstValue = "order";
        public static string CTmmtid = "flow.mmtid";
        public static int CTmmtidValue = 1;
        public static string CTherkomst = "flow.herkomst";
        public static Guid DebriefQuestionlistId;
        public static string ServiceorderId = "flow.serviceorder_id";
        public static int Form28BtnOntvangsten= 740;
        public static int FormOntvangsten = 38;
        public static int Form28BtnOrder = 1639;
        public static int Form28 = 28;
        public static string Form28BtnRetouren = "btnRetouren";
        public static int FormRetouren = 120;
        public static int FormBestellen = 110;
        public static string Form28BtnFreeOrder = "btnFreeOrder";
        public static string CTrprio = "app.t_rprio";
        public static int CTrprioValue = 1026102696;
        public static string Materialmutationreason6 = "36";
        public static string Materialmutationreason3 = "33";
        public static string QuestionlistId = "flow.questionlist_id";
        public static int QuestionlistIdValue = 9;
    }
}
